install:
  - ps: Start-FileDownload 'https://sonarsource.bintray.com/Distribution/sonarqube/sonarqube-5.1.2.zip'
  - ps: Start-FileDownload 'http://repo1.maven.org/maven2/org/codehaus/sonar/runner/sonar-runner-dist/2.4/sonar-runner-dist-2.4.zip'
  - cmd: unzip sonarqube-5.1.2.zip -d C:\tmp\
  - cmd: unzip sonar-runner-dist-2.4.zip -d C:\tmp\
  - cmd: set PATH=C:\tmp\sonar-runner-2.4\bin;%PATH%
  - cmd: git clone https://github.com/iwarapter/sonar-puppet.git C:\projects\
  - cmd: cd C:\projects\sonar-puppet
  - cmd: gem install puppet-lint

build_script:
  - gradlew clean build